import type { Presentation } from './types'

export const presentations: Presentation[] = [
  {
    id: 'p01',
    slug: 'diplus',
    index: 1,
    title: 'DiPlus',
    subtitle:
      'Telemetría diferencial de combustible — mapa de calor, gal/h por modelo, sensor de nivel y ranking de operadores.',
    author: 'O. Palomino',
    category: 'Telemetría · Producto',
    slides: 6,
    duration: '9 min',
    lastEdited: 'Hoy · 09:02',
    status: 'in-review',
    collaborators: 3,
    views: 12,
    cover: 'diplus',
    accent: 'vermilion',
    span: 'hero',
  },
  {
    id: 'p02',
    slug: 'helios',
    index: 2,
    title: 'Helios',
    subtitle: 'Product launch — spring window, full keynote treatment.',
    author: 'M. Reyes',
    category: 'Launch',
    slides: 18,
    duration: '12 min',
    lastEdited: 'Today · 09:14',
    status: 'draft',
    collaborators: 6,
    views: 12,
    cover: 'helios',
    accent: 'ochre',
    span: 'wide',
  },
  {
    id: 'p03',
    slug: 'edition-two',
    index: 3,
    title: 'Edition Two',
    subtitle: 'Brand refresh, second pass — palette, voice, motion.',
    author: 'L. Iturbe',
    category: 'Brand',
    slides: 32,
    duration: '24 min',
    lastEdited: '3 days ago',
    status: 'ready',
    collaborators: 3,
    views: 214,
    cover: 'roman',
    accent: 'ink',
    span: 'medium',
  },
  {
    id: 'p04',
    slug: 'letters-from-the-field',
    index: 4,
    title: 'Letters from the Field',
    subtitle: 'Customer research recap — twelve interviews, four geographies.',
    author: 'A. Castillo',
    category: 'Research',
    slides: 14,
    duration: '9 min',
    lastEdited: 'Last week',
    status: 'ready',
    collaborators: 2,
    views: 67,
    cover: 'letters',
    accent: 'sage',
    span: 'medium',
  },
  {
    id: 'p05',
    slug: 'five-year-vision',
    index: 5,
    title: 'Five-Year Vision',
    subtitle: 'Long-range plan — narrative draft for the partner offsite.',
    author: 'O. Palomino',
    category: 'Strategy',
    slides: 8,
    duration: '6 min',
    lastEdited: '12 hours ago',
    status: 'draft',
    collaborators: 1,
    views: 4,
    cover: 'numeral',
    accent: 'vermilion',
    span: 'tall',
  },
  {
    id: 'p06',
    slug: 'operating-rituals',
    index: 6,
    title: 'Operating Rituals',
    subtitle: 'How the team meets, decides, and ships — internal handbook.',
    author: 'D. Solano',
    category: 'Handbook',
    slides: 28,
    duration: '21 min',
    lastEdited: '2 weeks ago',
    status: 'ready',
    collaborators: 5,
    views: 312,
    cover: 'grid',
    accent: 'ink',
    span: 'medium',
  },
  {
    id: 'p07',
    slug: 'tokyo-field-notes',
    index: 7,
    title: 'Tokyo Field Notes',
    subtitle: 'A typographic study — signage, vending, transit, neon.',
    author: 'L. Iturbe',
    category: 'Essay',
    slides: 12,
    duration: '8 min',
    lastEdited: 'A month ago',
    status: 'archived',
    collaborators: 1,
    views: 540,
    cover: 'kanji',
    accent: 'vermilion',
    span: 'medium',
  },
  {
    id: 'p08',
    slug: 'onboarding-reimagined',
    index: 8,
    title: 'Onboarding, Reimagined',
    subtitle: 'First-week experience — flow, milestones, ceremony.',
    author: 'M. Reyes',
    category: 'People',
    slides: 16,
    duration: '11 min',
    lastEdited: '5 days ago',
    status: 'in-review',
    collaborators: 3,
    views: 41,
    cover: 'arrow',
    accent: 'sage',
    span: 'wide',
  },
]

export const stats = {
  inProduction: 8,
  archived: 24,
  contributors: 11,
  totalSlides: 152,
}
